export const menuItems = [
  {
    label: 'Video Player',
    id: 'video-player',
    description: 'The video player itself.',
    icon: 'fluent:filmstrip-play-16-filled',
    features: [
      {
        label: 'Container',
        id: 'video-player-container',
        description: 'The container for the video player.',
        icon: 'fluent:frame-16-regular',
        props: [
          {
            group: 'Border',
            label: 'Color',
            id: 'video-player-border-color',
            cssProperty: 'border-color',
            cssSelector: '.boxcast-player-container',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Border',
            label: 'Thickness',
            id: 'video-player-border-thickness',
            cssProperty: 'border-width',
            cssSelector: '.boxcast-player-container',
            input: {
              type: 'range',
              default: 0,
              min: 0,
              max: 20,
              step: 1,
            },
          },
          {
            group: 'Border',
            label: 'Style',
            id: 'video-player-border-style',
            cssProperty: 'border-style',
            cssSelector: '.boxcast-player-container',
            input: {
              type: 'select',
              default: 'none',
              options: [
                { label: 'None', value: 'none' },
                { label: 'Solid', value: 'solid' },
                { label: 'Dashed', value: 'dashed' },
                { label: 'Dotted', value: 'dotted' },
              ],
            },
          },
          {
            group: 'Border',
            label: 'Radius',
            id: 'video-player-border-radius',
            cssProperty: 'border-radius',
            cssSelector: '.boxcast-player-container',
            input: {
              type: 'range',
              default: 0,
              min: 0,
              max: 64,
              step: 4,
            },
          },
          {
            group: 'Border',
            label: 'Clip Overflow',
            id: 'video-player-clip-overflow',
            cssProperty: 'overflow',
            cssSelector: '.boxcast-player-container',
            input: {
              type: 'toggle',
              default: false,
            },
          },
        ],
      },
      {
        label: 'Large Play Button',
        id: 'large-play-button',
        description: 'Play button visible when player first loads.',
        icon: 'fluent:play-circle-28-filled',
        props: [
          {
            group: 'Button',
            label: 'Color',
            id: 'play-button-bg-color',
            cssProperty: 'background-color',
            cssSelector: '#boxcast-big-play-button',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Button',
            label: 'Width',
            id: 'play-button-width',
            cssProperty: 'width',
            cssSelector: '#boxcast-big-play-button',
            input: {
              type: 'range',
              default: 80,
              min: 20,
              max: 200,
              step: 5,
            },
          },
          {
            group: 'Button',
            label: 'Height',
            id: 'play-button-height',
            cssProperty: 'height',
            cssSelector: '#boxcast-big-play-button',
            input: {
              type: 'range',
              default: 80,
              min: 20,
              max: 200,
              step: 5,
            },
          },
          {
            group: 'Icon',
            label: 'Color',
            id: 'play-button-icon-color',
            cssProperty: 'fill',
            cssSelector: '#boxcast-big-play-button > svg > path',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Icon',
            label: 'Width',
            id: 'play-button-icon-width',
            cssProperty: 'width',
            cssSelector: '#boxcast-big-play-button > svg',
            input: {
              type: 'range',
              default: 80,
              min: 20,
              max: 200,
              step: 5,
            },
          },
          {
            group: 'Icon',
            label: 'Height',
            id: 'play-button-icon-height',
            cssProperty: 'height',
            cssSelector: '#boxcast-big-play-button > svg',
            input: {
              type: 'range',
              default: 80,
              min: 20,
              max: 200,
              step: 5,
            },
          },
        ],
      },
      {
        label: 'Controls',
        id: 'video-player-controls',
        description: 'Controls visible when player is active.',
        icon: 'fluent:video-play-pause-20-filled',
        props: [
          {
            group: 'Scrubber',
            label: 'Handle Color',
            id: 'controls-scrubber-handle-color',
            cssProperty: 'background-color',
            cssSelector: '.bar-scrubber-icon',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Scrubber',
            label: 'Progress Color',
            id: 'controls-scrubber-progress-color',
            cssProperty: 'background-color',
            cssSelector: '.bar-fill-2',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Scrubber',
            label: 'Buffered Color',
            id: 'controls-scrubber-buffered-color',
            cssProperty: 'background-color',
            cssSelector: '.bar-fill-1',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
        ],
      },
    ],
  },
  {
    label: 'Description Box',
    id: 'description-box',
    description: 'The description box below the video player.',
    icon: 'fluent:text-description-16-filled',
    features: [
      {
        label: 'Container',
        id: 'description-box-container',
        description: 'The container for the description box.',
        icon: 'fluent:frame-16-regular',
        props: [
          {
            group: 'Border',
            label: 'Color',
            id: 'description-box-border-color',
            cssProperty: 'border-color',
            cssSelector: '.boxcast-with-playlist-to-right-col-1 > .boxcast-well',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Border',
            label: 'Thickness',
            id: 'description-box-border-thickness',
            cssProperty: 'border-width',
            cssSelector: '.boxcast-with-playlist-to-right-col-1 > .boxcast-well',
            input: {
              type: 'range',
              default: 0,
              min: 0,
              max: 20,
              step: 1,
            },
          },
          {
            group: 'Border',
            label: 'Style',
            id: 'description-box-border-style',
            cssProperty: 'border-style',
            cssSelector: '.boxcast-with-playlist-to-right-col-1 > .boxcast-well',
            input: {
              type: 'select',
              default: 'none',
              options: [
                { label: 'None', value: 'none' },
                { label: 'Solid', value: 'solid' },
                { label: 'Dashed', value: 'dashed' },
                { label: 'Dotted', value: 'dotted' },
              ],
            },
          },
          {
            group: 'Border',
            label: 'Radius',
            id: 'description-box-border-radius',
            cssProperty: 'border-radius',
            cssSelector: '.boxcast-with-playlist-to-right-col-1 > .boxcast-well',
            input: {
              type: 'range',
              default: 0,
              min: 0,
              max: 64,
              step: 4,
            },
          },
          {
            group: 'Background',
            label: 'Color',
            id: 'description-box-background-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-with-playlist-to-right-col-1 > .boxcast-well',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.1)',
            },
          },
        ],
      },
      {
        label: 'Broadcast Title',
        id: 'description-broadcast-title',
        description: 'Name of the broadcast',
        icon: 'fluent:slide-text-title-16-filled',
        props: [
          {
            group: 'Typography',
            label: 'Color',
            id: 'broadcast-title-color',
            cssProperty: 'color',
            cssSelector: 'h1.boxcast-title',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.9)',
            },
          },
          {
            group: 'Typography',
            label: 'Size',
            id: 'broadcast-title-size',
            cssProperty: 'font-size',
            cssSelector: 'h1.boxcast-title',
            input: {
              type: 'range',
              default: 24,
              min: 12,
              max: 48,
              step: 1,
            },
          },
          {
            group: 'Typography',
            label: 'Weight',
            id: 'broadcast-title-weight',
            cssProperty: 'font-weight',
            cssSelector: 'h1.boxcast-title',
            input: {
              type: 'select',
              default: 400,
              options: [
                { label: 'Normal', value: 400 },
                { label: 'Bold', value: 700 },
              ],
            },
          },
        ],
      },
      {
        label: 'Broadcast Description',
        id: 'description-broadcast-description',
        description: 'The description text for the broadcast.',
        icon: 'fluent:subtitles-20-filled',
        props: [
          {
            group: 'Typography',
            label: 'Color',
            id: 'broadcast-description-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-description',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.8)',
            },
          },
          {
            group: 'Typography',
            label: 'Link Color',
            id: 'broadcast-description-link-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-description > * a',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.8)',
            },
          },
          {
            group: 'Typography',
            label: 'Size',
            id: 'broadcast-description-size',
            cssProperty: 'font-size',
            cssSelector: '.boxcast-description > *',
            input: {
              type: 'range',
              default: 14,
              min: 10,
              max: 24,
              step: 1,
            },
          },
          {
            group: 'Typography',
            label: 'Weight',
            id: 'broadcast-description-weight',
            cssProperty: 'font-weight',
            cssSelector: '.boxcast-description',
            input: {
              type: 'select',
              default: 400,
              options: [
                { label: 'Normal', value: 400 },
                { label: 'Bold', value: 700 },
              ],
            },
          },
        ],
      },
      {
        label: 'Start/Stop Times',
        id: 'description-start-stop-times',
        description: 'The scheduled start and stop times for the broadcast.',
        icon: 'fluent:clock-12-filled',
        props: [
          {
            group: 'Typography',
            label: 'Color',
            id: 'start-stop-times-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-start-stop',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.8)',
            },
          },
          {
            group: 'Typography',
            label: 'Size',
            id: 'start-stop-times-size',
            cssProperty: 'font-size',
            cssSelector: '.boxcast-start-stop',
            input: {
              type: 'range',
              default: 12,
              min: 10,
              max: 20,
              step: 1,
            },
          },
        ],
      },
      {
        label: 'Ticket Button',
        id: 'description-ticket-button',
        description: 'The ticket button for the broadcast.',
        icon: 'fluent:ticket-20-filled',
        props: [
          {
            group: 'Appearance',
            label: 'Background Color',
            id: 'ticket-button-bg-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-ticket > span:first-child > button.boxcast-ticket-button',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Appearance',
            label: 'Border Color',
            id: 'ticket-button-border-color',
            cssProperty: 'border-color',
            cssSelector: '.boxcast-ticket > span:first-child > button.boxcast-ticket-button',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Appearance',
            label: 'Text Color',
            id: 'ticket-button-text-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-ticket > span:first-child > button.boxcast-ticket-button',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
        ],
      },
      {
        label: 'Donate Button',
        id: 'description-donate-button',
        description: 'The donate button for the broadcast.',
        icon: 'fluent:heart-16-filled',
        props: [
          {
            group: 'Appearance',
            label: 'Background Color',
            id: 'donate-button-bg-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-ticket > span:nth-child(2) > button.boxcast-ticket-button',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Appearance',
            label: 'Border Color',
            id: 'donate-button-border-color',
            cssProperty: 'border-color',
            cssSelector: '.boxcast-ticket > span:nth-child(2) > button.boxcast-ticket-button',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Appearance',
            label: 'Text Color',
            id: 'donate-button-text-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-ticket > span:nth-child(2) > button.boxcast-ticket-button',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
        ],
      },
    ],
  },
  {
    label: 'Related Videos',
    id: 'related-videos',
    description: 'The playlist for viewing other broadcasts in the channel.',
    icon: 'fluent:text-bullet-list-square-16-filled',
    features: [
      {
        label: 'Container',
        id: 'playlist-container',
        description: 'The container for the related videos playlist.',
        icon: 'fluent:frame-16-regular',
        props: [
          {
            group: 'Background',
            label: 'Color',
            id: 'playlist-bg-color',
            cssProperty: 'background-color',
            cssSelector: 'div.boxcast-playlist',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Border',
            label: 'Color',
            id: 'playlist-border-color',
            cssProperty: 'border-color',
            cssSelector: 'div.boxcast-playlist',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Border',
            label: 'Thickness',
            id: 'playlist-border-thickness',
            cssProperty: 'border-width',
            cssSelector: 'div.boxcast-playlist',
            input: {
              type: 'range',
              default: 1,
              min: 0,
              max: 20,
              step: 1,
            },
          },
          {
            group: 'Border',
            label: 'Radius',
            id: 'playlist-border-radius',
            cssProperty: 'border-radius',
            cssSelector: 'div.boxcast-playlist',
            input: {
              type: 'range',
              default: 1,
              min: 0,
              max: 20,
              step: 1,
            },
          },
          {
            group: 'Border',
            label: 'Clip Overflow',
            id: 'playlist-clip-overflow',
            cssProperty: 'overflow',
            cssSelector: 'div.boxcast-playlist',
            input: {
              type: 'toggle',
              default: false,
            },
          },
        ],
      },
      {
        label: 'Heading Text',
        id: 'playlist-heading-text',
        description: "'Related Videos text'",
        icon: 'fluent:text-16-filled',
        props: [
          {
            group: 'Typography',
            label: 'Color',
            id: 'playlist-heading-color',
            cssProperty: 'color',
            cssSelector: 'div.boxcast-playlist > .boxcast-well-title > div > h3',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.9)',
            },
          },
          {
            group: 'Typography',
            label: 'Size',
            id: 'playlist-heading-size',
            cssProperty: 'font-size',
            cssSelector: 'div.boxcast-playlist > .boxcast-well-title > div > h3',
            input: {
              type: 'range',
              default: 18,
              min: 8,
              max: 32,
              step: 2,
            },
          },
        ],
      },
      {
        label: 'Search Bar',
        id: 'playlist-search-bar',
        description: 'The search bar for filtering related videos.',
        icon: 'fluent:search-16-filled',
        props: [
          {
            group: 'Spacing',
            label: 'Horizontal Padding',
            id: 'playlist-search-padding',
            cssProperty: 'padding-inline',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'range',
              default: 0,
              min: 0,
              max: 32,
              step: 1,
            },
          },
          {
            group: 'Spacing',
            label: 'Vertical Padding',
            id: 'playlist-search-padding-vertical',
            cssProperty: 'padding-block',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'range',
              default: 0,
              min: 0,
              max: 32,
              step: 1,
            },
          },
          {
            group: 'Spacing',
            label: 'Width',
            id: 'playlist-search-width',
            cssProperty: 'width',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'range',
              default: 130,
              min: 0,
              max: 280,
              step: 10,
            },
          },
          {
            group: 'Spacing',
            label: 'Height',
            id: 'playlist-search-height',
            cssProperty: 'height',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'range',
              default: 28,
              min: 28,
              max: 64,
              step: 4,
            },
          },
          {
            group: 'Color',
            label: 'Background',
            id: 'playlist-search-bg-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Color',
            label: 'Text',
            id: 'playlist-search-text-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Color',
            label: 'Placeholder',
            id: 'playlist-search-placeholder-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-playlist-search > input::placeholder',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.25)',
            },
          },
          {
            group: 'Color',
            label: 'Border',
            id: 'playlist-search-border-color',
            cssProperty: 'border-color',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.25)',
            },
          },
          {
            group: 'Border',
            label: 'Thickness',
            id: 'playlist-search-border-width',
            cssProperty: 'border-width',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'range',
              default: 1,
              min: 0,
              max: 8,
              step: 1,
            },
          },
          {
            group: 'Typography',
            label: 'Font Size',
            id: 'playlist-search-text-size',
            cssProperty: 'font-size',
            cssSelector: '.boxcast-playlist-search > input',
            input: {
              type: 'range',
              default: 16,
              min: 8,
              max: 32,
              step: 1,
            },
          },
        ],
      },
      {
        label: 'Playlist Items',
        id: 'playlist-items',
        description: 'The list of related videos.',
        icon: 'fluent:list-16-filled',
        props: [
          {
            group: 'Color',
            label: 'Broadcast Title',
            id: 'playlist-item-title-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-playlist-item-meta > h3',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.9)',
            },
          },
          {
            group: 'Color',
            label: 'Broadcast Description',
            id: 'playlist-item-description-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-playlist-item-meta > p:nth-child(2)',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.9)',
            },
          },
          {
            group: 'Color',
            label: 'Broadcast Date-Time',
            id: 'playlist-item-datetime-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-playlist-item-meta > p:nth-child(3)',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.9)',
            },
          },
        ],
      },
      {
        label: 'Pagination Controls',
        id: 'playlist-pagination-controls',
        description: 'The pagination controls for the playlist.',
        icon: 'fluent:arrow-next-12-filled',
        props: [
          {
            group: 'Color',
            label: 'Background',
            id: 'playlist-pagination-bg-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-page-controls',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Color',
            label: 'Label',
            id: 'playlist-pagination-label-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-page-controls > span',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Color',
            label: 'Button Background',
            id: 'playlist-pagination-button-bg-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-page-controls > a',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Color',
            label: 'Button Text',
            id: 'playlist-pagination-button-text-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-page-controls > a',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
        ],
      },
    ],
  },
  {
    label: 'Viewer Chat',
    id: 'viewer-chat',
    description: 'The window for viewer chat messages.',
    icon: 'fluent:people-chat-20-filled',
    features: [
      {
        label: 'Container',
        id: 'chat-container',
        description: 'The container for the viewer chat.',
        icon: 'fluent:frame-16-regular',
        props: [
          {
            group: 'Border',
            label: 'Color',
            id: 'chat-border-color',
            cssProperty: 'border-color',
            cssSelector: '.boxcast-chat--shell',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Border',
            label: 'Radius',
            id: 'chat-border-radius',
            cssProperty: 'border-radius',
            cssSelector: '.boxcast-chat--shell',
            input: {
              type: 'range',
              default: 0,
              min: 0,
              max: 16,
              step: 1,
            },
          },
          {
            group: 'Border',
            label: 'Thickness',
            id: 'chat-border-width',
            cssProperty: 'border-width',
            cssSelector: '.boxcast-chat--shell',
            input: {
              type: 'range',
              default: 1,
              min: 0,
              max: 16,
              step: 1,
            },
          },
          {
            group: 'Background',
            label: 'Color',
            id: 'chat-background-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-chat--shell, .boxcast-chat--msgcontainer',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
        ],
      },
      {
        label: 'Header',
        id: 'chat-header',
        description: 'The header for the viewer chat.',
        icon: 'fluent:text-16-filled',
        props: [
          {
            group: 'Layout',
            label: 'Flex Alignment',
            id: 'chat-header-alignment',
            cssProperty: 'align-items',
            cssSelector: '.boxcast-chat--shell > .boxcast-well-title',
            input: {
              type: 'select',
              default: 'start',
              options: [
                { label: 'Start', value: 'start' },
                { label: 'Center', value: 'center' },
                { label: 'End', value: 'end' },
              ],
            },
          },
          {
            group: 'Typography',
            label: 'Color',
            id: 'chat-header-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-chat--shell > .boxcast-well-title > h3',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.9)',
            },
          },
          {
            group: 'Typography',
            label: 'Size',
            id: 'chat-header-size',
            cssProperty: 'font-size',
            cssSelector: '.boxcast-chat--shell > .boxcast-well-title > h3',
            input: {
              type: 'range',
              default: 18,
              min: 8,
              max: 32,
              step: 2,
            },
          },
        ],
      },
      {
        label: 'Messages',
        id: 'chat-messages',
        description: 'The viewer chat messages.',
        icon: 'fluent:chat-16-filled',
        props: [
          {
            group: 'Color',
            label: 'Bubble',
            id: 'chat-message-bubble-color',
            cssProperty: 'background-color',
            cssSelector: '.boxcast-chat--msgcontainer .boxcast-chat--msg',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
          {
            group: 'Color',
            label: 'Message Text',
            id: 'chat-message-text-color',
            cssProperty: 'color',
            cssSelector: '.boxcast-chat--msg:not(strong)',
            input: {
              type: 'color',
              default: 'hsla(0, 0, 0, 0.5)',
            },
          },
        ],
      },
    ],
  },
  {
    label: 'Experimental',
    id: 'experimental-features',
    description: 'Features that are in development or testing.',
    icon: 'fluent:beaker-16-filled',
    features: [
      {
        label: 'No Gaps',
        id: 'experimental-no-gaps',
        description: 'Removes gaps between player components for a more seamless look.',
        icon: 'fluent:eraser-20-filled',
      },
      {
        label: 'Modern Description Order',
        id: 'experimental-modern-description-order',
        description: 'Reorders the description box elements for a more modern look.',
        icon: 'fluent:layout-row-three-20-filled',
      },
    ],
  },
]
